import os

class Config:
    DATABASE_URL = os.getenv('DATABASE_URL')
    SOCIAL_MEDIA_API_KEY = os.getenv('SOCIAL_MEDIA_API_KEY')
    PAYMENT_GATEWAY_API_KEY = os.getenv('PAYMENT_GATEWAY_API_KEY')
    NLP_API_KEY = os.getenv('NLP_API_KEY')
    SPEECH_RECOGNITION_API_KEY = os.getenv('SPEECH_RECOGNITION_API_KEY')
    TEXT_TO_SPEECH_API_KEY = os.getenv('TEXT_TO_SPEECH_API_KEY')
    NEWS_API_KEY = os.getenv('NEWS_API_KEY')
    WEATHER_API_KEY = os.getenv('WEATHER_API_KEY')
    OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
    BUILDERIO_API_KEY = os.getenv('BUILDERIO_API_KEY')

APP_CONFIG = Config()