apiVersion: v1 
clusters: 
- cluster: 
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekV3TURneQpNekF3TURoYUZ3MDBNekV3TURneU16QXdNRGhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEUXN3endyeWhINVBHQmtVQ05mSHhudmVFUVdnZFBFVlJKMW1iQ0o4eUdGeFdpbHErcAp1WEFaQStOTGJIa2VpcmkzR0dRVWg0aVFwRGExZlRIS28zOXVpOURNaFZxdjl1VmM3WjlpV0ZyZVQ4WWZKY1hUClE0VmJhTUFibnB6VGQySVA4STJQck4xcVZPMHBGZEF5TEt6clRrTDlJajkzNE9ZeDhlenBoNDNoeEZwZEFmWHYKZGVUNE1JQVZOK3dUT3pncmpUN055c013RTRlWThvMGFZMENvVGxScmcwRUZ2R3FYa1hxV0ZoQnhiT2h2ZklOSgpvSHh0QnhJK2xtTURsOS9UTUdITURMalpwa1dkUDBZcUVvRDI0UjdsVGlKTVRTWm4vQUE1cEJXRTBGNVNiYmZYCnBSVDZGVDZqUTlPejhITnFQVlE2b0p3M2pwRzZ5eUFGOFBaREFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRaU0JxSFA0MlRhV0NHM2dyWQpWdTNBVDlnQTV6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFlYjloU0JoUU93MGpUQXVzQUxsVXZ2UW9VNERlClhpYWRoQ2RpZFRrSTlUazAveTFBaUVicDc1akVKNCtxTFdBaEpmK3hjTHB3TDlYbGppcTk5S2dEQ09vYVZ0clkKMFNnMUVGK2lYZyt3QjdvRkdkd0o1Z081Ulg3Y0UwaDZsVG14b2VtVWd4MGNYUjJ0VktSZG9rZFlKZVRJQnRtbApiSkNyOC8rZHFiTk8xdVA2UDNHdzByMC8vUlpxcFVqQi9ybDNSMFNDaXpzNjJWVmp1Q3JxNDQ3ZEtlbnNERzRzCkllZGZtNzk5dGVVQ3h2V096TjRsaEZGWlNKVUl3Q0FXKzgzNlQ3dUJtaFVSdHV2d0JaNktYSEJQWGNXZGQrNVAKc2VFNkFuRXBtby9ERXJ3MmM3dEtkcEN6Y1ZhZDZyOUltMW12emR3Wk1MeUJ1MmVtMmZKWGFLRnRHUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K     
    server: https://9a543c80-6a1f-447e-8c7c-9b040ef0fb08.k8s.ondigitalocean.com   
    name: do-sfo3-modaltokai 
contexts: 
- context:     
    cluster: do-sfo3-modaltokai     
    user: do-sfo3-modaltokai-admin   
    name: do-sfo3-modaltokai 
current-context: do-sfo3-modaltokai 
kind: Config 
preferences: {} 
users: 
- name: do-sfo3-modaltokai-admin   
  user: 
    token: dop_v1_e96ea9c3dde5636658bb1a6b095082f2391d5bfe6e03d74066bdc801c261f3cf
- context:
    cluster: cert-manager
    user: cert-manager\admin
    name: cert-manager
- name: cert-manager\admin
  user:
    token: <TOKEN FOR CERT-MANAGER>
current-context: cert-manager
preferences:
  helm:
    upgrade:
      cert-manager:
        version: <CERT_MANAGER_NEW_VERSION>
        values: <YOUR_HELM_VALUES_FILE>
  tls:
    issuer: letsencrypt-nginx
    secretName: letsencrypt-nginx
  uninstall: 
    namespace: cert-manager
# Adding the ServiceNow CI/CD Batch Install action
actions:
- name: ServiceNow CI/CD Batch Install
  uses: ServiceNow/sncicd-batch-install@2.0.1 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "your-load-balancer-id"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: nginx-example
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "your-load-balancer-id"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
    service.beta.kubernetes.io/do-loadbalancer-deny-rules: "cidr:198.51.100.0/16"
    service.beta.kubernetes.io/do-loadbalancer-allow-rules: "ip:203.0.113.24,ip:203.0.113.68"
spec:
  type: LoadBalancer
  selector:
    app: nginx-example
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80