
# This is the Kubernetes configuration file for the application.
# It contains information on the services in use and their access tokens.
apiVersion: v1 
clusters: 
- cluster: 
    # This is the certificate authority data for the clusters in use.
    # It is an important part of the security of the Kubernetes configuration
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekV3TURneQpNekF3TURoYUZ3MDBNekV3TURneU16QXdNRGhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEUXN3endyeWhINVBHQmtVQ05mSHhudmVFUVdnZFBFVlJKMW1iQ0o4eUdGeFdpbHErcAp1WEFaQStOTGJIa2VpcmkzR0dRVWg0aVFwRGExZlRIS28zOXVpOURNaFZxdjl1VmM3WjlpV0ZyZVQ4WWZKY1hUClE0VmJhTUFibnB6VGQySVA4STJQck4xcVZPMHBGZEF5TEt6clRrTDlJajkzNE9ZeDhlenBoNDNoeEZwZEFmWHYKZGVUNE1JQVZOK3dUT3pncmpUN055c013RTRlWThvMGFZMENvVGxScmcwRUZ2R3FYa1hxV0ZoQnhiT2h2ZklOSgpvSHh0QnhJK2xtTURsOS9UTUdITURMalpwa1dkUDBZcUVvRDI0UjdsVGlKTVRTWm4vQUE1cEJXRTBGNVNiYmZYCnBSVDZGVDZqUTlPejhITnFQVlE2b0p3M2pwRzZ5eUFGOFBaREFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRaU0JxSFA0MlRhV0NHM2dyWQpWdTNBVDlnQTV6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFlYjloU0JoUU93MGpUQXVzQUxsVXZ2UW9VNERlClhpYWRoQ2RpZFRrSTlUazAveTFBaUVicDc1akVKNCtxTFdBaEpmK3hjTHB3TDlYbGppcTk5S2dEQ09vYVZ0clkKMFNnMUV...

# Some more modification and comments here

# Adding the ServiceNow CI/CD Batch Install action
actions:
- name: ServiceNow CI/CD Batch Install
# This action is used to carry out the CI/CD process in ServiceNow.
# It is not the main service of the application, but a crucial part
# of its development and deployment process.
uses: ServiceNow/sncicd-batch-install@2.0.1 

# The other services and their configurations are defined below
---
apiVersion: v1
kind: Service
metadata:
# This is the service for the nginx server.
# It is responsible for handling HTTP requests.
name: nginx
annotations:
kubernetes.digitalocean.com/load-balancer-id: "your-load-balancer-id"
spec:
type: LoadBalancer
selector:
app: nginx-example
ports:
- name: http
protocol: TCP
port: 80
targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
# This is the service for the nginx server.
# It is responsible for handling HTTP requests.
name: nginx
annotations:
kubernetes.digitalocean.com/load-balancer-id: "your-load-balancer-id"
spec:
type: LoadBalancer
selector:
app: nginx-example
ports:
- name: http
protocol: TCP
port: 80
targetPort: 80
