# The following is the resolved version of modal.py after resolving conflicts on pull 18
# Generated by helper

from django import template
from django.utils.safestring import mark_safe

register = template.Library()


@register.simple_tag
def modal(modal_id, modal_title='', modal_body='', modal_footer=''):
    return mark_safe(f"""
        <div id="{modal_id}" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">{modal_title}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>{modal_body}</p>
                    </div>
                    <div class="modal-footer">
                        {modal_footer}
                    </div>
                </div>
            </div>
        </div>
    """)