# Default values for Smodal chart.
# This is a YAML-formatted file.
# You can declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sobereyed/modaltokai
  pullPolicy: IfNotPresent
  # Override the image tag to deploy using the `--set tag` option
  # via helm install
  tag: 

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}